name: Deploy to Vercel
description: Deploy to Vercel
inputs:
  VERCEL_PROJECT_ID:
    description: Vercel project ID
    required: true
  VERCEL_TOKEN:
    description: Vercel token
    required: true
  ENVIRONMENT:
    description: Environment
    required: true

runs:
  using: composite
  steps:
    - name: Install Vercel CLI
      shell: bash
      run: |
        echo "Installing Vercel CLI..."
        npm install -g vercel@latest
        vercel --version

    - name: Configure Vercel
      shell: bash
      env:
        VERCEL_TOKEN: ${{ inputs.VERCEL_TOKEN }}
      run: |
        # Clean up
        rm -rf .vercel

        # Create new configuration
        mkdir -p .vercel
        echo "{\"version\":2,\"projectId\":\"${{ inputs.VERCEL_PROJECT_ID }}\",\"github\":{\"enabled\":false}}" > vercel.json
        
        # Verify configuration
        cat vercel.json

    - name: Deploy
      shell: bash
      env:
        VERCEL_TOKEN: ${{ inputs.VERCEL_TOKEN }}
      run: |
        vercel deploy --prod --token=$VERCEL_TOKEN --yes